# Generated by Django 2.1.1 on 2018-09-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='article_attachments'),
        ),
    ]
